# Generated by Django 3.2.8 on 2021-10-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20211029_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolors',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
