# Generated by Django 3.2.8 on 2021-10-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211022_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfos',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfos',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfos',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfos',
            name='phone',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
