# Generated by Django 3.2.8 on 2021-10-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211028_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfos',
            name='email',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfos',
            name='facebook',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='personalinfos',
            name='first_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfos',
            name='instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='personalinfos',
            name='last_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfos',
            name='phone',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfos',
            name='tiktok',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='personalinfos',
            name='youtube',
            field=models.URLField(blank=True, default=''),
        ),
    ]
