# Generated by Django 3.2.8 on 2021-10-28 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_auto_20211028_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfos',
            name='id',
        ),
        migrations.AlterField(
            model_name='personalinfos',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='infos', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
