# Generated by Django 3.2.8 on 2021-10-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20211028_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfos',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinfos',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinfos',
            name='tiktok',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinfos',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
